### ISSUE TITLE
Option winrmPassword type to 'Secure' wouldn't work

### ISSUE THREAD

**Issue by EwyynTomato** [rundeck-plugins/rundeck-winrm-plugin#13]
I'm not sure if this is intended or not, but setting RunDeck option: winrmPassword type to 'Secure' instead of 'Secure Remote Authentication' wouldn't work. 

This is caused by option type:'Secure' wouldn't expose the key and value in context.getPrivateDataContext().

This is also causing a bit of headache as 'Secure Remote Authentication' doesn't seem to work with scheduled job in Rundeck.

**Comment by dlcampbell888** [comment]
Seconding this.  Secure Remote Authentication does not work in a scheduled job so we can't use it for any scheduled jobs..

[overthere-winrm:172.18.11.131] Password was not set
Failed: ConfigurationFailure: Password was not set

The job works as expected when run manually..

[overthere-winrm:172.18.11.131] ConnectionOptions[ port --> 5985 os --> WINDOWS username --> Administrator address --> 172.18.11.131 winrmEnableHttps --> false winrmKerberosAddPortToSpn --> false connectionType --> WINRM connectionTimeoutMillis --> 15000 winrmKerberosUseHttpSpn --> false password --> ******** ]

**Comment by gschueler** [comment]
scheduled job will be able to use key storage #26
