### ISSUE TITLE
WinRM plugin still failing with Java 1.7

### ISSUE THREAD

**Issue by danifr** [rundeck-plugins/rundeck-winrm-plugin#19]
I updated the plugin to the latest version (https://github.com/rundeck-plugins/rundeck-winrm-plugin/issues/16 thanks!) but it still fails (Overthere error: Unexpected HTTP response on http://rundeckserver:5985/wsman: (401)) when Java 1.7.0_67 is installed.

Same machine, same configuration, different Java version (1.6.0_32) and it works like a charm.
Is this only happening to me?

**Comment by gschueler** [comment]
ref #33

**Comment by gschueler** [comment]
#39
