### ISSUE TITLE
plugin not loading

### ISSUE THREAD

**Issue by mathieuchateau** [rundeck-plugins/rundeck-winrm-plugin#24]
Hello,

i copied the jar in libext folder with others one. No way to get it in "List plugins" menu on rundeck.
I am using java 1.6.0.34
i check the right & owner of the file to be same as others.

No clue from rundeck logs.

Any idea?

regards,

**Comment by gschueler** [comment]
what rundeck version are you using?

**Comment by mathieuchateau** [comment]
Hello,

Thanks for helping.

At the time of writing it was on latest version in 2.4.2-1.

Now i am on 2.5.0.1, but i do not see it neither.

**Comment by gschueler** [comment]
if you don't see the plugin in the List Plugins list, or as an option for Node Executor when you edit/create a project, then it seems like the plugin is not being loaded.  

how is rundeck installed, rpm?

**Comment by samuraitaiga** [comment]
I had same problem and resolved by below.
problem is plugin owner is wrong.

I changed owner from root to rundeck.
`#chown rundeck. /var/lib/rundeck/libext/rundeck-winrm-plugin-1.3.1.jar`

And also change permission to 644 as same as other plugins.
`# chmod 644 /var/lib/rundeck/libext/rundeck-winrm-plugin-1.3.1.jar`

this is my environment 
os: CentOS release 6.6 (Final)
rundeck version: 2.5.1 (installed via rpm)

**Comment by mathieuchateau** [comment]
Hello,

thanks a lot, you put me on track.

Setting owner and chmod was not enough, I also had to upgrade to
version rundeck-winrm-plugin-1.3.1 (instead of 1.2)

Now I also have plugin ready and so I can start playing with my Windows
server :)




Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-06-02 7:15 GMT+02:00 Taiga Murakami <notifications@github.com>:
