### ISSUE TITLE
Winrm authentication problem

### ISSUE THREAD

**Issue by jamesarems** [rundeck-plugins/rundeck-winrm-plugin#27]
Hi,
Im trying to connect rundeck to my windows machine, every thing i tried based on secure authentication method , But now im getting like below,.

"[overthere-winrm:10.254.254.88] Password was not set
	Failed: ConfigurationFailure: Password was not set"

My resources.xml entry is,

"node name="MyWinPC" node-executor="overthere-winrm" username="administrator" hostname="10.254.254.88:5985" winrm-protocol="http" winrm-auth-type="basic" description="Windows server node" tags="windows" osArch="x86_64" osFamily="windows" osName="Windows 8" winrm-password-option="winrmPassword" "

Where i need to edit?
In windows ,Is there  any option like ssh key ?

**Comment by jamesarems** [comment]
"<node name="MyWinPC" node-executor="overthere-winrm" username="james" hostname="10.254.254.88:5985" winrm-protocol="http" winrm-auth-type="basic" description="Windows server node" tags="windows" osArch="x86_64" osFamily="windows" osName="Windows 8" winrm-password-option="winrmPassword"
  />"

**Comment by jamesarems** [comment]
node name="MyWinPC" node-executor="overthere-winrm" username="james" hostname="10.254.254.88:5985" winrm-protocol="http" winrm-auth-type="basic" description="Windows server node" tags="windows" osArch="x86_64" osFamily="windows" osName="Windows 8" winrm-password-option="winrmPassword"

**Comment by gschueler** [comment]
Your need to define a Job, and declare a "Secure Remote Authentication" option with the same name "winrmPassword".

Otherwise, you can use the Key Storage system to store your password, and use the `winrm-password-storage-path` attribute.

**Comment by jamesarems** [comment]
Thanks for your reply,
Can you please give a demo resources.xml entry of windows node , that will be great.
I know its a tough task but any how i need to do this.

**Comment by herrygoon** [comment]
<?xml version="1.0" encoding="UTF-8"?>

<project> 
  <node name="GSP-PC2" description="Rundeck node" tags="" hostname="192.168.21.7" osArch="x86" osFamily="windows" osName="Windows 7" osVersion="6.1" username="dy" winrm-password-option="winrmPassword" />
</project>


![1](https://cloud.githubusercontent.com/assets/473702/8372276/52bcf066-1c14-11e5-9b4f-1fd1d5840221.jpg)
![2](https://cloud.githubusercontent.com/assets/473702/8372274/52b782b6-1c14-11e5-8d48-2cc3eabcf4ce.jpg)
![3](https://cloud.githubusercontent.com/assets/473702/8372275/52baef64-1c14-11e5-8a1c-abd4eb6673a2.jpg)


And the Job define is:
<joblist>
  <job>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo password</exec>
      </command>
    </sequence>
    <dispatch>
      <threadcount>1</threadcount>
      <keepgoing>false</keepgoing>
      <excludePrecedence>true</excludePrecedence>
      <rankOrder>ascending</rankOrder>
    </dispatch>
    <nodefilters>
      <filter>winrm-password-option: .*</filter>
    </nodefilters>
    <loglevel>INFO</loglevel>
    <name>TestPassword</name>
    <context>
      <project>demo2</project>
      <options>
        <option name='winrmPassword' secure='true' />
      </options>
    </context>
    <description></description>
    <id>12b903de-4dd7-4072-980c-33405eb08ed0</id>
    <uuid>12b903de-4dd7-4072-980c-33405eb08ed0</uuid>
  </job>
</joblist>

**Comment by jamesarems** [comment]
Hi @herrygoon ,
Thanks it helps me a lot . Now Its working fine. 
This link also help full. http://www.diegoluisi.eti.br/2015/06/linux/rundeck-how-to-add-windows-node/

**Comment by sourav-sarkar** [comment]
I have followed all the things from this site http://www.techpaste.com/2015/08/rundeck-windows-nodes-configuration/ 
but when I am running a job I was getting the same problem . I did everything above mentioned but it is saying "Authentication failure connecting to node: "win_node". Password incorrect." though password is correct for sure as I can ssh to that node using winrm.
Can you help me please?
