### ISSUE TITLE
support winrm basic auth for domain users

### ISSUE THREAD

**Issue by lmayorga1980** [rundeck-plugins/rundeck-winrm-plugin#30]
Not sure if this is related but I found a way to authenticate a domain user who is a member of the **Local Administrators Group** using **Winrm Ruby Gem** (https://rubygems.org/gems/winrm/versions/1.3.3).

It seems that the WinRM implementation in ruby works for this scenario but for some reason I get on Rundeck that it is not supported to use **DOMAIN\USERNAME** on the **winrm-user** setting.

``` ruby

require 'winrm'

host = ARGV[0]
cmd  = ARGV[1]
endpoint = "http://#{host}:5985/wsman"
winrm = WinRM::WinRMWebService.new(endpoint, :plaintext, :user => '<DOMAIN>\<USERNAME>t', :pass => '<password>', :basic_auth_only => false)

winrm.cmd("#{cmd}") do |stdout, stderr|
    STDOUT.print stdout
      STDERR.print stderr
end 
```

**Comment by vvchik** [comment]
well, may be because it is java library?

**Comment by sksirajbasha** [comment]
Hi .. Were anyone able to get a success with this ?

**Comment by ltamaster** [comment]
Hi @lmayorga1980 

Please take a look to [here](https://github.com/xebialabs/overthere#domain-accounts)

I think this plugin use the WINRM_INTERNAL connection type so you cannot use the  DOMAIN\USERNAME format, instead you need USER@FULL.DOMAIN format.

If you cannot do that I recommend you others plugins, like the [python winrm plugin](https://github.com/rundeck-plugins/py-winrm-plugin) or ruby.
