### ISSUE TITLE
Please create new package using Overthere 4.1.1

### ISSUE THREAD

**Issue by aadi4u** [rundeck-plugins/rundeck-winrm-plugin#33]
Can you please build another package using Overthere 4.1.1

**Comment by gschueler** [comment]
was there a specific issue/bugfix that 4.1.1 fixes for you?

**Comment by aadi4u** [comment]
Yes. HTTP 401 response while using Kerberos with a domain account . I tried to build the package myself but it is giving class load errors. Not sure what went wrong. Thanks for your help in advance.

 # Release History
+* Overthere 4.1.1 (26-Aug-2015)
+    * Fixed bug where WINRM_INTERNAL connection with Windows domain account failed with error message "Unexpected HTTP response on http://hostname/wsman: (401)".
 * Overthere 4.1.0 (18-Aug-2015)
     * Fixed bug where temporary files were not deleted for a CIFS/WINRM_INTERNAL or a CIFS/TELNET connection when connection was closed.
     * Fixed bug where short-circuit copy would fail with error message "tar: can't set time on .: Not owner". This could occur when copying from/to a temporary file/directory for an SSH/SU, SSH/SUDO or SSH/INTERACTIVE_SUDO connection.

**Comment by pecigonzalo** [comment]
:+1:

**Comment by omar-yassin** [comment]
+1. Having the same issue with the kerberos (401) error.

**Comment by nfrankish** [comment]
We are also having this issue on Java 1.7
Any eta?

**Comment by rasebo** [comment]
Same issues here, it would be great if we could use winrm with domain accounts.

**Comment by ssbarnea** [comment]
I would say that's a bug and not e feature, the ability to run commands on windows as domain accounts is critical because this is the only safe way to run administrative commands related to Active Directory. Without having this solved, we can say that the rundeck support for Windows is mostly missing.

**Comment by bbc88ks** [comment]
Would be nice to have, also hit by this issue :/

**Comment by gschueler** [comment]
hi all, I submitted a PR for overthere addressing a bug https://github.com/xebialabs/overthere/pull/169 and hoping it can be merged soon, but not sure when the next overthere release incorporating that patch would be. in the meantime I can update the winrm plugin using latest overthere, I'm hoping to get to this soon.

**Comment by bbc88ks** [comment]
Could you please update the plugin using the latest version while your pull request is in review? That would be amazing, thanks!

**Comment by gschueler** [comment]
released 1.3.2 with overthere upgrade to 4.2.1
