### ISSUE TITLE
I keep getting unwanted output

### ISSUE THREAD

**Issue by Ronsevet** [rundeck-plugins/rundeck-winrm-plugin#36]
Keep getting this, every time I run a PS job,
Job runs successfully but this keeps poping in the output. 
removeScriptPluginCache: /var/lib/rundeck/libext/cache/rd-winrm-plugin-1.3.2 for: /var/lib/rundeck/libext/rd-winrm-plugin-1.3.2.zip

**Comment by gschueler** [comment]
what rundeck version?

**Comment by gschueler** [comment]
this is a rundeck bug, refiling it there: https://github.com/rundeck/rundeck/issues/1749
