### ISSUE TITLE
Store passwords in a file

### ISSUE THREAD

**Issue by deeptowncitizen** [rundeck-plugins/rundeck-winrm-plugin#48]
I'm trying to configure WinRM with **winrm-password-storage-path**

<node name="<name>" winrm-auth-type="basic" node-executor="overthere-winrm" username="user" hostname="<some-ip>" osArch="amd64" osFamily="windows" osName="Windows" winrm-password-storage-path="/var/lib/rundeck/win-keys" />

What I can see from [this](https://github.com/rundeck-plugins/rundeck-winrm-plugin/pull/26/commits/c6a4078517eb6cf0e1e8aa1f3930a3806eeb4cf6) change is that it simply reads some file and gets password from it. So I need to specify **winrm-password-storage-path** and put some file there with password content?

1. What is the filename?
2. Is there any way not to store password in open way? Only configuration with winrm-password-option?

I create file with node name and tried different extensions, also tried to specify full filename.
Executing the job I'm getting error, e.g. path does not exist

**Comment by dmitry-reshetnik** [comment]
For the moment I'm using Security Option.
But getting an error:

> Failed: WinRMProtocolError: WinRM Error: Error when sending request to http://my-host:5985/wsmanRequest:
> <?xml version="1.0" encoding="UTF-8"?>
> 
> <env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope">
>   <env:Header>
>     <a:To xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing">http://my-host:5985/wsman</a:To>
>     <a:ReplyTo xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing">
>       <a:Address mustUnderstand="true">http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:Address>
>     </a:ReplyTo>
>     <w:MaxEnvelopeSize xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" mustUnderstand="true">153600</w:MaxEnvelopeSize>
>     <a:MessageID xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing">uuid:22ECF3E1-35E4-4BEF-8F8A-767F926BA282</a:MessageID>
>     <w:Locale xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" mustUnderstand="false" xml:lang="en-US"/>
>     <p:DataLocale xmlns:p="http://schemas.microsoft.com/wbem/wsman/1/wsman.xsd" mustUnderstand="false" xml:lang="en-US"/>
>     <w:OperationTimeout xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd">PT60.000S</w:OperationTimeout>
>     <a:Action xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing" mustUnderstand="true">http://schemas.xmlsoap.org/ws/2004/09/transfer/Create</a:Action>
>     <w:ResourceURI xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" mustUnderstand="true">http://schemas.microsoft.com/wbem/wsman/1/windows/shell/cmd</w:ResourceURI>
>     <w:OptionSet xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd">
>       <w:Option Name="WINRS_NOPROFILE">FALSE</w:Option>
>       <w:Option Name="WINRS_CODEPAGE">437</w:Option>
>     </w:OptionSet>
>   </env:Header>
>   <env:Body>
>     <rsp:Shell xmlns:rsp="http://schemas.microsoft.com/wbem/wsman/1/windows/shell">
>       <rsp:InputStreams>stdin</rsp:InputStreams>
>       <rsp:OutputStreams>stdout stderr</rsp:OutputStreams>
>     </rsp:Shell>
>   </env:Body>
> </env:Envelope>

**Comment by deeptowncitizen** [comment]
For the moment I'm using Security Option.
But getting an error:

> Failed: WinRMProtocolError: WinRM Error: Error when sending request to http://my-host:5985/wsmanRequest:
> <?xml version="1.0" encoding="UTF-8"?>
> 
> <env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope">
>   <env:Header>
>     <a:To xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing">http://my-host:5985/wsman</a:To>
>     <a:ReplyTo xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing">
>       <a:Address mustUnderstand="true">http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:Address>
>     </a:ReplyTo>
>     <w:MaxEnvelopeSize xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" mustUnderstand="true">153600</w:MaxEnvelopeSize>
>     <a:MessageID xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing">uuid:22ECF3E1-35E4-4BEF-8F8A-767F926BA282</a:MessageID>
>     <w:Locale xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" mustUnderstand="false" xml:lang="en-US"/>
>     <p:DataLocale xmlns:p="http://schemas.microsoft.com/wbem/wsman/1/wsman.xsd" mustUnderstand="false" xml:lang="en-US"/>
>     <w:OperationTimeout xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd">PT60.000S</w:OperationTimeout>
>     <a:Action xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing" mustUnderstand="true">http://schemas.xmlsoap.org/ws/2004/09/transfer/Create</a:Action>
>     <w:ResourceURI xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" mustUnderstand="true">http://schemas.microsoft.com/wbem/wsman/1/windows/shell/cmd</w:ResourceURI>
>     <w:OptionSet xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd">
>       <w:Option Name="WINRS_NOPROFILE">FALSE</w:Option>
>       <w:Option Name="WINRS_CODEPAGE">437</w:Option>
>     </w:OptionSet>
>   </env:Header>
>   <env:Body>
>     <rsp:Shell xmlns:rsp="http://schemas.microsoft.com/wbem/wsman/1/windows/shell">
>       <rsp:InputStreams>stdin</rsp:InputStreams>
>       <rsp:OutputStreams>stdout stderr</rsp:OutputStreams>
>     </rsp:Shell>
>   </env:Body>
> </env:Envelope>

**Comment by gschueler** [comment]
@deeptowncitizen it is not a file, it is stored in the [key storage](http://rundeck.org/docs/manual/configure.html#key-storage) system.  You can configure it to store in the DB or in the filesystem, and it can be encrypted, see [storage facility](http://rundeck.org/docs/administration/storage-facility.html)
