### ISSUE TITLE
Username not read from project.winrm-user 

### ISSUE THREAD

**Issue by atahir** [rundeck-plugins/rundeck-winrm-plugin#6]
Hi, 

Even if I specify a password for the winrm using the project.winrm-user setting in the project.properties file my job is not picking it up. However when I set the username attribute on the node definition in resource.xml it is ok.

Has any one come across this problem. 

Thanks for your help.

**Comment by gschueler** [comment]
username resolution picks the first one of these that is present:

1. `node.username`
2. user@`node.hostname` (looks for user@hostname) pattern in the node hostname
3. `node.winrm-user`
4. `project.winrm-user`
5. `framework.winrm-user`

**Comment by jvdp11** [comment]
is there a way to override this? For me, resources.xml provides a username that I would like to override at certain jobs.

**Comment by gschueler** [comment]
sorry, you can override on a per-job basis, but you will *always* have specify it via the job.

e.g. you can have the node `username="${option.username}"` and have a job option called "username"

**Comment by jvdp11** [comment]
i guess I can work with that, thanks!
